#database:
  driver: "org.postgresql.Driver"
  password: "admin"
  url: "jdbc:postgresql://172.31.254.93:5432/prototype"
  username: "postgres"
#person:
  create: "insert into personne (nom, age) values(?,?)"
  delete: "delete from personne where id=?"
  read: "select * from personne order by id"
  update: "update personne set nom=?,age=? where id=?"
#connexion config
listenPort: 1099
soTimeout: 2000
ip : "172.31.254.93"
